apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    categories: A list of comma separated categories that your operator falls under.
    certified: "false"
    containerImage: ""
    createdAt: "2026-03-27T18:39:42Z"
    description: OpenShift cluster provisioning and management at scale.
    olm.operatorGroup: openshift-cluster-monitoring
    olm.operatorNamespace: openshift-monitoring
    olm.skipRange: '>=0.0.1 <0.1.826-g81d9d24'
    olm.targetNamespaces: dynatrace,hypershift,hypershift-control-plane-log-forwarding,open-cluster-management-agent-addon,openshift-addon-operator,openshift-apiserver,openshift-apiserver-operator,openshift-authentication,openshift-authentication-operator,openshift-aws-vpce-operator,openshift-catalogd,openshift-cloud-controller-manager,openshift-cloud-controller-manager-operator,openshift-cloud-credential-operator,openshift-cloud-network-config-controller,openshift-cluster-csi-drivers,openshift-cluster-machine-approver,openshift-cluster-node-tuning-operator,openshift-cluster-samples-operator,openshift-cluster-storage-operator,openshift-cluster-version,openshift-codeready-workspaces,openshift-compliance-monkey,openshift-config-operator,openshift-console,openshift-console-operator,openshift-controller-manager,openshift-controller-manager-operator,openshift-custom-domains-operator,openshift-deployment-validation-operator,openshift-dns,openshift-dns-operator,openshift-etcd-operator,openshift-image-registry,openshift-ingress,openshift-ingress-operator,openshift-insights,openshift-kube-apiserver,openshift-kube-apiserver-operator,openshift-kube-controller-manager,openshift-kube-controller-manager-operator,openshift-kube-scheduler,openshift-kube-scheduler-operator,openshift-kube-storage-version-migrator,openshift-kube-storage-version-migrator-operator,openshift-logging,openshift-machine-api,openshift-machine-config-operator,openshift-managed-node-metadata-operator,openshift-managed-upgrade-operator,openshift-marketplace,openshift-monitoring,openshift-multus,openshift-must-gather-operator,openshift-network-console,openshift-network-diagnostics,openshift-network-node-identity,openshift-network-operator,openshift-oauth-apiserver,openshift-observability-operator,openshift-ocm-agent-operator,openshift-operator-controller,openshift-operator-lifecycle-manager,openshift-osd-metrics,openshift-ovn-kubernetes,openshift-package-operator,openshift-rbac-permissions,openshift-route-controller-manager,openshift-route-monitor-operator,openshift-security,openshift-service-ca-operator,openshift-user-workload-monitoring,openshift-validation-webhook
    operatorframework.io/properties: '{"properties":[{"type":"olm.package","value":{"packageName":"configure-alertmanager-operator","version":"0.1.826-g81d9d24"}}]}'
    support: OSD SRE
  creationTimestamp: "2026-04-17T16:16:42Z"
  finalizers:
  - operators.coreos.com/csv-cleanup
  generation: 1
  labels:
    olm.managed: "true"
    operators.coreos.com/configure-alertmanager-operator.openshift-monitoring: ""
  name: configure-alertmanager-operator.v0.1.826-g81d9d24
  namespace: openshift-monitoring
  resourceVersion: "329344624"
  uid: f87257c7-797b-4f70-b189-c2653bad0688
spec:
  apiservicedefinitions: {}
  cleanup:
    enabled: false
  customresourcedefinitions: {}
  description: SRE operator - configure-alertmanager-operator
  displayName: configure-alertmanager-operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - nodes
          verbs:
          - get
          - list
        - apiGroups:
          - config.openshift.io
          resources:
          - clusterversions
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - config.openshift.io
          resources:
          - proxies
          - infrastructures
          verbs:
          - get
          - list
          - watch
        serviceAccountName: configure-alertmanager-operator
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          - configmaps
          verbs:
          - get
          - list
          - watch
          - patch
          - update
        - apiGroups:
          - batch
          resources:
          - jobs
          verbs:
          - get
          - list
          - watch
        serviceAccountName: configure-alertmanager-operator
      deployments:
      - name: configure-alertmanager-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: configure-alertmanager-operator
          strategy: {}
          template:
            metadata:
              annotations:
                openshift.io/required-scc: restricted-v2
              creationTimestamp: null
              labels:
                name: configure-alertmanager-operator
            spec:
              affinity:
                nodeAffinity:
                  preferredDuringSchedulingIgnoredDuringExecution:
                  - preference:
                      matchExpressions:
                      - key: node-role.kubernetes.io/infra
                        operator: Exists
                    weight: 1
              containers:
              - command:
                - configure-alertmanager-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: configure-alertmanager-operator
                - name: FEDRAMP
                  value: "false"
                - name: OPERATOR_IMAGE
                  value: quay.io/app-sre/configure-alertmanager-operator@sha256:25472958f253b0019f890233345a6a6a96deb43bc6005b93526beae09f469e76
                image: quay.io/app-sre/configure-alertmanager-operator@sha256:25472958f253b0019f890233345a6a6a96deb43bc6005b93526beae09f469e76
                imagePullPolicy: Always
                name: configure-alertmanager-operator
                resources:
                  limits:
                    cpu: 200m
                    memory: 1Gi
              serviceAccountName: configure-alertmanager-operator
              tolerations:
              - effect: NoSchedule
                key: node-role.kubernetes.io/infra
                operator: Exists
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - configure-alertmanager-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        serviceAccountName: configure-alertmanager-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - kubernetes
  - openshift
  - multi-cluster
  - cluster
  maturity: alpha
  provider:
    name: Red Hat, Inc
  replaces: configure-alertmanager-operator.v0.1.824-g0fd5305
  version: 0.1.826-g81d9d24
status:
  cleanup: {}
  conditions:
  - lastTransitionTime: "2026-04-17T16:16:42Z"
    lastUpdateTime: "2026-04-17T16:16:42Z"
    message: requirements not yet checked
    phase: Pending
    reason: RequirementsUnknown
  - lastTransitionTime: "2026-04-17T16:16:42Z"
    lastUpdateTime: "2026-04-17T16:16:42Z"
    message: all requirements found, attempting install
    phase: InstallReady
    reason: AllRequirementsMet
  - lastTransitionTime: "2026-04-17T16:16:42Z"
    lastUpdateTime: "2026-04-17T16:16:42Z"
    message: waiting for install components to report healthy
    phase: Installing
    reason: InstallSucceeded
  - lastTransitionTime: "2026-04-17T16:16:42Z"
    lastUpdateTime: "2026-04-17T16:16:43Z"
    message: 'installing: waiting for deployment configure-alertmanager-operator to
      become ready: deployment "configure-alertmanager-operator" waiting for 1 outdated
      replica(s) to be terminated'
    phase: Installing
    reason: InstallWaiting
  - lastTransitionTime: "2026-04-17T16:16:46Z"
    lastUpdateTime: "2026-04-17T16:16:46Z"
    message: install strategy completed with no errors
    phase: Succeeded
    reason: InstallSucceeded
  - lastTransitionTime: "2026-04-26T19:35:24Z"
    lastUpdateTime: "2026-04-26T19:35:24Z"
    message: 'installing: waiting for deployment configure-alertmanager-operator to
      become ready: deployment "configure-alertmanager-operator" not available: Deployment
      does not have minimum availability.'
    phase: Failed
    reason: ComponentUnhealthy
  - lastTransitionTime: "2026-04-26T19:35:24Z"
    lastUpdateTime: "2026-04-26T19:35:24Z"
    message: 'installing: waiting for deployment configure-alertmanager-operator to
      become ready: deployment "configure-alertmanager-operator" not available: Deployment
      does not have minimum availability.'
    phase: Pending
    reason: NeedsReinstall
  - lastTransitionTime: "2026-04-26T19:35:25Z"
    lastUpdateTime: "2026-04-26T19:35:25Z"
    message: all requirements found, attempting install
    phase: InstallReady
    reason: AllRequirementsMet
  - lastTransitionTime: "2026-04-26T19:35:28Z"
    lastUpdateTime: "2026-04-26T19:35:28Z"
    message: waiting for install components to report healthy
    phase: Installing
    reason: InstallSucceeded
  - lastTransitionTime: "2026-04-26T19:35:28Z"
    lastUpdateTime: "2026-04-26T19:35:29Z"
    message: 'installing: waiting for deployment configure-alertmanager-operator to
      become ready: deployment "configure-alertmanager-operator" not available: Deployment
      does not have minimum availability.'
    phase: Installing
    reason: InstallWaiting
  - lastTransitionTime: "2026-04-26T19:38:20Z"
    lastUpdateTime: "2026-04-26T19:38:20Z"
    message: install strategy completed with no errors
    phase: Succeeded
    reason: InstallSucceeded
  lastTransitionTime: "2026-04-26T19:38:20Z"
  lastUpdateTime: "2026-04-26T19:38:20Z"
  message: install strategy completed with no errors
  phase: Succeeded
  reason: InstallSucceeded
  requirementStatus:
  - dependents:
    - group: rbac.authorization.k8s.io
      kind: PolicyRule
      message: cluster rule:{"verbs":["get","list"],"apiGroups":[""],"resources":["nodes"]}
      status: Satisfied
      version: v1
    - group: rbac.authorization.k8s.io
      kind: PolicyRule
      message: cluster rule:{"verbs":["get","list","watch"],"apiGroups":["config.openshift.io"],"resources":["clusterversions"]}
      status: Satisfied
      version: v1
    - group: rbac.authorization.k8s.io
      kind: PolicyRule
      message: cluster rule:{"verbs":["get","list","watch"],"apiGroups":["config.openshift.io"],"resources":["proxies","infrastructures"]}
      status: Satisfied
      version: v1
    - group: rbac.authorization.k8s.io
      kind: PolicyRule
      message: cluster rule:{"verbs":["get","list","watch","patch","update"],"apiGroups":[""],"resources":["secrets","configmaps"]}
      status: Satisfied
      version: v1
    - group: rbac.authorization.k8s.io
      kind: PolicyRule
      message: cluster rule:{"verbs":["get","list","watch"],"apiGroups":["batch"],"resources":["jobs"]}
      status: Satisfied
      version: v1
    group: ""
    kind: ServiceAccount
    message: ""
    name: configure-alertmanager-operator
    status: Present
    version: v1
